os: osx
osx_image: xcode10.2

matrix:
  include:
    - language: node_js
      os: linux
      node_js:
        - "12"

      install:
        - cd website
        - yarn
        - cd ..

      script:
        - cd website
        - yarn build
        - cd ..

      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          fqdn: fbflipper.com
          local-dir: website/build
          keep-history: true
          on:
            branch: master
    - language: node_js
      os: linux
      node_js:
        - "12"

      install:
        - cd desktop
        - yarn

      script:
        - yarn lint
        - yarn test
        - yarn build --linux --version=$TRAVIS_BUILD_NUMBER
