[package]
name = "flipper-packer"
version = "0.1.0"
authors = ["Facebook, Inc."]
edition = "2018"

[dependencies]
clap = "^2.33.1"
shellexpand = "^2.0.0"
tar = "^0.4.26"
serde = { version = "^1.0.106", features = ["derive"] }
serde_yaml = "^0.8.11"
anyhow = "^1.0.31"
sha2 = "^0.8.1"
data-encoding = "^2.2.0"
serde_json = "^1.0.52"
rayon = "^1.3.0"
indicatif = "^0.14.0"
xz2 = "^0.1.6"

[dev-dependencies]
tempdir = "^0.3.7"
