name:                bump
version:             0.2.3

dependencies:
  - base >= 4.7 && < 5
  - turtle
  - system-filepath
  - foldl
  - text

executables:
  bump:
    source-dirs:      .
    main:             bump.hs
