name: Publish DMG App On Release

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: macos-latest
    env:
      desktop-directory: ./desktop

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install
      run: yarn
      working-directory: ${{env.desktop-directory}}
    - name: Build
      run: yarn build --mac --mac-dmg
      working-directory: ${{env.desktop-directory}}
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: 'Flipper-mac.dmg'
        path: 'dist/Flipper-mac.dmg'
  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download
      uses: actions/download-artifact@v1
      with:
        name: 'Flipper-mac.dmg'
        path: 'Flipper-mac.dmg'
    - run: ls -la Flipper-mac.dmg
    - name: Publish
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'Flipper-mac.dmg'
